In [14]:
import cv2
import numpy

In [5]:
im_g=cv2.imread("Desktop/smallgray.png", 0)
im_g


array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [6]:
cv2.imwrite("newimage.png", im_g)

True

In [8]:
im_g[0:2, 2:4 ]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [12]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [16]:
ims=numpy.hstack((im_g, im_g))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)